### ISSUE TITLE
NullPointerException in SimpleBufferTest

### ISSUE THREAD

**Issue by SirMathhman** [Meticuli-Technologies/Block2P#15]
java.lang.NullPointerException
	at com.meti.io.buffer.SimpleBufferTest.lambda$test$0(SimpleBufferTest.java:41)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$7(AssertTimeout.java:97)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$10(AssertTimeout.java:117)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by SirMathhman** [comment]
It's know that #3 and this one both involve concurrency because the tests can fail or run, it depends on the synchronization of the internal buffer. Going to use a repeated test.
